Style/CaseIndentation:
  IndentOneStep: true
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
Style/NumericLiterals:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%r": "()"
Style/SingleLineBlockParams:
  Enabled: true
Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Metrics/LineLength:
  Max: 120
AllCops:
  Exclude:
    - '*.gemspec'
    - 'Rakefile'
    - 'spec/support/*/*.rb'
    - 'Guardfile'

